### ISSUE TITLE
function addItem(type, index) type mistake

### ISSUE THREAD

**Issue by philj0st** [phipix01/neoHUS#3]
![Image of Chrome Console](http://s8.postimg.org/nmyn5wzg5/2015_03_27_13_25_00_neo_HUS.png)

**index + i** results in "20" instead of the expected (2+0) because an idiot passed in a string for index :stuck_out_tongue_closed_eyes:

**Comment by p-kiser** [comment]
#like

**Comment by KilnOfTheSecondFlame** [comment]
Should be fixed after the last commit, please test
And stop trying to break the code :smile:

**Comment by philj0st** [comment]
@KilnOfTheSecondFlame :shipit: well no need for type checking in each function don't worry. it just realized i was the idiot who passed the string into the function after i created the issue and then edited the comment :blush: 
Roger would be proud of your friendliness to nitpicking Collaborators :trollface:

**Comment by KilnOfTheSecondFlame** [comment]
No worries, learned some intricancies of javascript in the process:
http://united-coders.com/matthias-reuter/handling-the-unexpected-type-safe-functions-in-javascript/
